openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /recipe/{id}:
    put:
      tags:
        - recipe-controller
      operationId: updateRecipe
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Recipe'
    delete:
      tags:
        - recipe-controller
      operationId: deleteRecipeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Recipe'
  /recipe:
    get:
      tags:
        - recipe-controller
      operationId: getAllRecipes
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
    post:
      tags:
        - recipe-controller
      operationId: addNewRecipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Recipe'
  /recipe/{ingredientName}:
    get:
      tags:
        - recipe-controller
      operationId: getByIngredientName
      parameters:
        - name: ingredientName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        quantity:
          type: string
        recipe_id:
          type: integer
          format: int64
    Instruction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        step_number:
          type: integer
          format: int32
        step_description:
          type: string
        recipe_id:
          type: integer
          format: int64
    Recipe:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        ingredients:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        instructions:
          type: array
          items:
            $ref: '#/components/schemas/Instruction'
